export { default as Homeimg1} from "./home-slider-img5.jpg"
export { default as Homeimg2} from "./home-banner-copper-billets-img.jpg"
export { default as Homeimg3} from "./home-banner-aluminium-ingots.jpg"
export { default as Homeimg4} from "./home-slider-img4.jpg"
export { default as Homeimg5} from "./hm_banner-1.jpg"
export { default as ServiceImage1} from "./hm_banner-1.jpg"
export { default as ServiceImage2} from "./hm_banner-1.jpg"
export { default as ServiceImage3} from "./hm_banner-1.jpg"
export { default as ServiceImage4} from "./hm_banner-1.jpg"
export { default as About} from "./JRR.jpeg"
export { default as product1} from "./hos-img6.jpg"
export { default as product2} from "./hos-img1.jpg"
export { default as product3} from "./hos-img2.jpg"
export { default as product4} from "./hos-img4.jpg"
export { default as worldmap} from "./gfp-marker-worldmap (1).png"
export { default as client1} from "./young-man-happy-expression-business-desk-company-concept-ai-generated.jpg"
export { default as client2} from "./young-entrepreneur.jpg"
export { default as client3} from "./successful-businessman.jpg"
export { default as aboutbanner} from "./WhatsApp Image 2025-06-04 at 13.27.05_33bbae95.jpg"