export { default as Productimg1} from "./COPPER-Wire-Scrap-q7v2kahquwxz7c06u7egw9tkps5hn4ktieggsvxw3c.jpg"
export { default as Productimg2} from "./copper-Brich-Cliff-1-q7v2kahquwxz7c06u7egw9tkps5hn4ktieggsvxw3c.jpg"
export { default as Productimg3} from "./copper-bus-bar-punching-scraps-500x500-2-q7v2kreu9xl50bbm3epr55jvepu3hofzkq77fv8szc.png"
export { default as Productimg4} from "./copper-wire-scrap-500x500-2-q7v2kqh033juopcz8wb4knsetbyq9zc98ljpyla75k.jpg"
export { default as Banner} from "./copper-recycling-banner-img.jpg"
export { default as plant} from "./JRPL.jpeg"
export { default as Alluminum} from "./aluminium-wire-scrap-for-metal-industry-2222953049-pkt6mxqk.jpg"
export { default as Allbanner} from "./aluminium-recycling-banner-img.jpg"
export { default as Contact} from "./istockphoto-879441788-612x612.jpg"
export { default as recycle1} from "./p1.jpg"
export { default as recycle2} from "./p2.jpg"
export { default as recycle3} from "./p3.jpg"
export { default as recycle4} from "./p4.jpg"
export { default as recyclea} from "./a1.jpg"
export { default as recycleI} from "./industry-construction-equipments-inside-storehouse-factory.jpg"
export { default as m1} from "./p5 (1).jpg"
export { default as m2} from "./p5 (2).jpg"
export { default as m3} from "./p5 (3).jpg"
export { default as m4} from "./p5 (4).jpg"
export { default as m5} from "./p5 (5).jpg"