export { default as Productimg1} from "./COPPER-Wire-Scrap-q7v2kahquwxz7c06u7egw9tkps5hn4ktieggsvxw3c.jpg"
export { default as Productimg2} from "./copper-Brich-Cliff-1-q7v2kahquwxz7c06u7egw9tkps5hn4ktieggsvxw3c.jpg"
export { default as Productimg3} from "./copper-bus-bar-punching-scraps-500x500-2-q7v2kreu9xl50bbm3epr55jvepu3hofzkq77fv8szc.png"
export { default as Productimg4} from "./copper-wire-scrap-500x500-2-q7v2kqh033juopcz8wb4knsetbyq9zc98ljpyla75k.jpg"
export { default as Banner} from "./copper-recycling-banner-img.jpg"
export { default as plant} from "./JRPL.jpeg"
export { default as Alluminum} from "./aluminium-wire-scrap-for-metal-industry-2222953049-pkt6mxqk.jpg"
export { default as Allbanner} from "./aluminium-recycling-banner-img.jpg"
export { default as Contact} from "./istockphoto-879441788-612x612.jpg"
export { default as recycle1} from "./p1.jpg"
export { default as recycle2} from "./p2.jpg"
export { default as recycle3} from "./WhatsApp Image 2025-05-15 at 15.28.57_43da3d02.jpg"
export { default as recycle4} from "./p4.jpg"
export { default as recyclea} from "./a1.jpg"
export { default as recycleI} from "./industry-construction-equipments-inside-storehouse-factory.jpg"
export { default as m1} from "./p5 (1).jpg"
export { default as m2} from "./p5 (2).jpg"
export { default as m3} from "./p5 (3).jpg"
export { default as m4} from "./p5 (4).jpg"
export { default as m5} from "./p5 (5).jpg"
export { default as pic} from "./contctus.png"
export { default as pic1} from "./career.png"
export { default as pic2} from "./steel.png"
export { default as pic3} from "./aboutbck.png"
export { default as pic4} from "./servicebck.png"
export { default as img1} from "./O&M.png"
export { default as img2} from "./Intra.png"
export { default as img3} from "./Railway.png"

export { default as img4} from "./Scrap.png"
export { default as img5} from "./Material.png"
export { default as img6} from "./Mining Excavation.png"
export { default as img7} from "./Port Operations.png"
export { default as img8} from "./Aerospace.png"
export { default as img9} from "./Heavy Equipment.png"
export { default as img10} from "./Petrochemical Supply.png"
export { default as picture1} from "./Leadership.png"
export { default as picture2} from "./Sales.png"
export { default as picture3} from "./Logistic.png"
export { default as picture4} from "./Qulaity.png"
export { default as picture5} from "./Aboutbackground.png"

